// <auto-generated />
// Generated by JSON Tools. Do not edit manually.

using System.Collections.Generic;

public class QuestPhaseTemplate
{
    public string Id { get; set; }
    public string Description { get; set; }
    public string Stat { get; set; }
    public int DcModifier { get; set; }
    public string Position { get; set; }
    public List<string> ForTypes { get; set; }
}

public class PhaseTemplateDatabase
{
    public List<QuestPhaseTemplate> Phases { get; set; } = new();
}
